name: MySQL Test
on: push
jobs:
  mysql_test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: shutdown ubuntu MySQL
        run: sudo service mysql stop

      - name: set up mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_bin'
          mysql version: '5.7'
          mysql database: 'huga'
          mysql root password: 'password'

      #      - name: mkdir
      #        run: sudo mkdir -p /var/run/mysqld
      #
      #      - name: touch
      #        run: sudo touch /var/run/mysqld/mysqld.sock
      #
      #      - name: chown
      #        run: sudo chown mysql:mysql /var/run/mysqld/mysqld.sock
      #
      #      - name: chmod
      #        run: sudo chmod 774 /var/run/mysqld/mysqld.sock

      - name: ping mysql 2
        run: echo $(mysqladmin -h127.0.0.1 -uroot -ppassword ping)

        #      - name: check mysql 1
        #        run: ps ax | grep mysqld
        #
        #      - name: aaa
        #        run: sleep 10

      - name: ping retry
        run: $(for i in 1 2 3 4 5; do mysqladmin -h127.0.0.1 -uroot -ppassword ping && break || sleep 5 && [ 5 -eq $i ] && exit 1 ; done)

      - name: ping mysql 3
        run: echo $(mysqladmin -h127.0.0.1 -uroot -ppassword ping)

      - name: check mysql 2
        run: mysql -h127.0.0.1 -P3306 -uroot -ppassword -Dhuga -e"SELECT '1'"

      - name: ping mysql 4
        run: echo $(mysqladmin -h127.0.0.1 -uroot -ppassword ping)


